name: R graph gallery
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:title/
url: http://elenius.github.io/rgraphgallery
author:
    name: Micke
    twitter: #
exclude:
    - LICENSE
    - README.md
    - CNAME
    - rgraphgallery.Rproj
    - /R
    - /R-plots
    - create_gallery.R
